# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 83851d0bce00a380b2f3dd9bdcc1269038ae11eafcdc4970f34d152cde201b24589e6be1c1b4fd65aa49f7ef6cc15672a634d74cea5405fb2382c59944044435

test:
  secret_key_base: cb84c3644c5b5e6a50cb50303fe40d40bdda5894c80dc9df678fe99294a7b5a8161e2016e974e473b619e00723b9a277cb395b7e103657d47634cc4a1854fbec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
